homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('favs/', views.favorites, name='favorites'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('courses/', include('story5.urls')),
    path('activity/', include('story6.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('addCourse/', views.addCourse, name='add'),
    path('', views.courses_show, name = 'courses'),
    path('<int:id>/', views.course_remove, name = 'course_remove'),

]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.activity, name = 'activity'),
    path('activityForm/', views.addActivity, name='addActivity'),
    path('addPerson/<int:person_id>/', views.addPerson, name='addPerson'),
    path('delete/<int:remove_id>/', views.removeActivity, name = 'removeActivity'),
]

homepage/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

story5/models.py
from django.db import models


# Create your models here.
class Courses(models.Model):
    name = models.CharField(max_length = 100)
    lecturer = models.CharField(max_length = 100)
    credit = models.IntegerField()
    room = models.CharField(max_length = 50)
    semester = models.CharField(max_length = 9)
    description = models.CharField(max_length = 500, null = True)



    

story6/models.py
from django.db import models

# Create your models here.
class Activity(models.Model) :
    activity = models.CharField(max_length = 100)
    def __str__(self):
        return self.activity


class Person(models.Model) : 
    person = models.CharField(max_length = 100)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.person

story5/forms.py
from django import forms

class CoursesForm(forms.Form):

    name = forms.CharField(
        label = 'Course Name',
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'type' : 'text',
                'required': True,
                'autocomplete' : 'off',
            }
        )
    )

    lecturer = forms.CharField(
        label = "Lecturer", 
        max_length = 100,
        widget = forms.TextInput (
            attrs={
                'class':'form-control',
                'type' : 'text',
                'required': True,
                'autocomplete' : 'off',
            }
        )
    )

    credit = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'class':'form-control',
                'min':'1',
                'max':'6'
            }
        )
    )

    room = forms.CharField(
        label = "Room", 
        max_length = 50,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'type' : 'text',
                'autocomplete' : 'off',
                'required': True,
            }
        )
    )

    semester = forms.CharField(
        label = "Semester", 
        max_length = 9,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'type' : 'text',
                'autocomplete' : 'off',
                'required': True,
                'placeholder' : 'Year Start / Year End'
            }
        )
    )

    description = forms.CharField(
        label = "Description", 
        max_length = 500,
        widget = forms.Textarea(
            attrs={
                'class':'form-control',
                'autocomplete' : 'off',
            }
        )
    )




    

story6/forms.py
from django import forms

class ActivityForm(forms.Form):
    
    activity = forms.CharField(
        label = 'Activity Name',
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'type' : 'text',
                'required': True,
                'autocomplete' : 'off',
            }
        )
    )
class PersonForm(forms.Form):
    
    person = forms.CharField(
        label = 'Name',
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'type' : 'text',
                'required': True,
                'autocomplete' : 'off',
            }
        )
    )

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'main.html')

def favorites(request):
    return render(request, 'secondPage.html')

story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story1.html')

story5/views.py
from django.shortcuts import render,redirect
from .models import Courses
from . import forms
from .forms import CoursesForm


def courses(request) :
    return render(request, 'story5.html')

def addCourse(request):
    formCourse = forms.CoursesForm()
    if request.method == 'POST':
        formInput = forms.CoursesForm(request.POST)
        if formInput.is_valid():
            data = formInput.cleaned_data
            inputData = Courses()
            inputData.name = data['name']
            inputData.lecturer = data['lecturer']
            inputData.credit = data['credit']
            inputData.room = data['room']
            inputData.semester = data['semester']
            inputData.description = data['description']
            inputData.save()
            return redirect('/courses')
        else:
            current_data = Courses.objects.all()
            return render(request, 'addCourse.html',{'form':formCourse, 'status':'failed','data':current_data})
    else:
        current_data = Courses.objects.all()
        return render(request, 'addCourse.html' ,{'form':formCourse,' data':current_data})

def courses_show(request):
    course = Courses.objects.all().order_by('credit').order_by('name')
    response = {
        'course':course, 
    }
    return render(request,'story5.html', response)

def course_remove(request, id):
    Courses.objects.filter(id=id).delete()
    course = Courses.objects.all().order_by('credit').order_by('name')
    response = {
        'course':course, 
    }
    return render(request, 'story5.html', response)

story6/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Activity, Person
from .forms import ActivityForm, PersonForm

def activity(request) :
    activity = Activity.objects.all().order_by('activity')
    person = Person.objects.all()
    response = {
        'activity': activity, 
        'person': person,
    }
    return render(request, 'activity.html', response)

def addActivity(request) :
    activityForm = ActivityForm()
    if request.method == "POST":
        inputForm = ActivityForm(request.POST)
        if inputForm.is_valid():
            data = inputForm.cleaned_data
            activityInput = Activity()
            activityInput.activity = data['activity']
            activityInput.save()
            return redirect('/activity/')
        else:
            return render(request, 'addActivity.html', {
                'form': activityForm, 
                'status': 'failed'
            })
    else :
        return render(request, 'addActivity.html', {
            'form': activityForm
        })

def addPerson(request, person_id) :
    personForm = PersonForm()
    if request.method == "POST":
        personInput = PersonForm(request.POST)
        if personInput.is_valid():
            data = personInput.cleaned_data
            newPerson = Person()
            newPerson.person = data['person']
            newPerson.activity = Activity.objects.get(id=person_id)
            newPerson.save()
            return redirect('/activity/')
        else :
            return render(request, 'addPerson.html', {
                'form': personForm, 
                'status': 'failed'
            })
    else:
        return render(request, 'addPerson.html', {
            'form': personForm,
        })

def removeActivity(request, remove_id) :
    activity = Activity.objects.all().order_by('activity')
    person = Person.objects.all()
    deleteUser = Person.objects.get(id=remove_id)
    deleteUser.delete()
    return redirect('/activity/')

homepage/templates/main.html
{% extends 'navbar.html' %}
{% load static%}
{% block content %}
    <img src="{% static 'photo.png' %}" class="photo">

    <h2> Raniah Nur Hanami </h2>


    <h3> About Me </h3>
    <em> Hello! My name is Raniah. I am a student of computer science in University of Indonesia, class of 2019. 
    I'm a fun and full-of-spirit person. I like to communicate with other people and that what makes me an adaptable person. 
    I really like sports, especially soccer and softball.
    </em>
    
    <h3> Skills and Interest </h3>
    <p>
        Team Work
        <br> Responsible
        <br> Flexibility 
        <br> Time Management
        <br> Volunteering
    </p>
    
    <h3> Educational Background </h3>
    <ul>
        <li class="eb"> University of Indonesia : 2019 - now </li>
        <li class="eb"> SMAN 5 Bogor : 2016 - 2019  </li>
        <li class="eb"> SMPN 4 Bogor : 2013 - 2016 </li>
        <li class="eb"> SDN Sukadamai 3 Bogor : 2007 - 2013</li>
    </ul> 



        <h3> Committee and Organization Experience </h3>
        <p class = "co"> Volunteer at Panda Mobile WWF Indonesia
        <p class = "co"> Staff of Playground Division at COMPFEST 12 </p>
        <p class = "co"> Vice Person in Charge of Liaison Officer at Open House Fasilkom UI 2020 </p>
        <p class = "co"> Student Mentor at PMB 2020 </p>
        <p class = "co"> Staff of Futsal Planner at PERAK Fasilkom UI </p>
        <p class = "co"> Staff of Event Division at Wisuda Ganjil 2020 </p>
        <p class = "co"> Secretarty at Runtime Error 5.0 </p>
        <p class = "co"> Vice Person in Charge of Event Division at Social Project 2019 </p>


    <div id = "gallery" class="jumbotron">
        <h1>  Gallery </h1>
        <p class ="gallery"> A bunch of images about my journey </p>
    </div>  

    <div class="row">
        <div class= "col-lg-4 col-sm-6">
            <img class="pict" src="{% static '1.jpg' %}">
        </div>
        <div class= "col-lg-4 col-sm-6">
            <img class="pict" src="{% static '2.jpg' %}">
        </div>
        <div class= "col-lg-4 col-sm-6"> 
            <img class="pict" src="{% static '3.jpg' %}">
        </div>

        <div class= "col-lg-4 col-sm-6">
            <img class="pict" src="{% static '4.jpg' %}">
        </div>
        <div class= "col-lg-4 col-sm-6">
            <img class="pict" src="{% static '6.jpg' %}">
        </div>
        <div class= "col-lg-4 col-sm-6"> 
            <img class="pict" src="{% static '5.jpg' %}">
        </div>      

        <div class= "col-lg-4 col-sm-6">
            <img class="pict" src="{% static '7.png' %}">
        </div>
        <div class= "col-lg-4 col-sm-6">
            <img class="pict" src="{% static '8.jpg' %}">
        </div>
        <div class= "col-lg-4 col-sm-6"> 
            <img class="pict" src="{% static '9.png' %}">
        </div> 
    </div>
    <div class="socmed">
        <span> Reach me at&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
        <a href="https://www.instagram.com/ranianhanami/" class="fa fa-instagram"></a>
        <a href="https://www.linkedin.com/in/raniah-nur-hanami-01336b194/" class="fa fa-linkedin"></a>
        <span class="email"> ranianurhanami@gmail.com  </span>
    </div>
{% endblock %}

homepage/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html> 
    <head> 
        <title> Raniah Nur Hanami </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"> </script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body> 
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'homepage:index' %}">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house-door-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6.5 10.995V14.5a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5h-4a.5.5 0 0 1-.5-.5V11c0-.25-.25-.5-.5-.5H7c-.25 0-.5.25-.5.495z"/>
                    <path fill-rule="evenodd" d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                </svg>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu" aria-controls="navbarTogglerDemo02" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="menu">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:index' %}#gallery">Gallery</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:favorites' %}">Favorites</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" data-toggle="popover" href="{% url 'story1:index' %}"> Story 1</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" data-toggle="popover" href="{% url 'story5:courses' %}"> Courses</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" data-toggle="popover" href="{% url 'story6:activity' %}"> Activities</a>
                    </li>
                    
                </ul>
            </div>
        </nav>
        <br>
        {% block content %}
        {% endblock %}
    </body>
<html>

homepage/templates/secondPage.html
{% extends 'navbar.html' %}
{% load static%}
{% block content %}
        <div class="card w-100">
            <div class="card-body">
                <h5 class="card-title fav">Favorites</h5>
                <p class="card-text">This page will be about my favorite things.</p>
            </div>
        </div>
        <br>
        
        <h3> Favorite Songs</h3>
        <br>
        <div class="row row-cols-1 row-cols-md-4">
            <div class="col mb-4">
                <iframe src="https://open.spotify.com/embed/track/4xqrdfXkTW4T0RauPLv3WA" width="230rem" height="380rem" frameborder="0" allowfullscreen ="true" allow="encrypted-media"></iframe>
            </div>
            <div class="col mb-4">
                <iframe src="https://open.spotify.com/embed/track/77SiKnkNEnRw0uoPE4wuEp" width="230rem" height="380rem" frameborder="0" allowfullscreen ="true" allow="encrypted-media"></iframe>
            </div>
            <div class="col mb-4">
                <iframe src="https://open.spotify.com/embed/track/4LEK9rD7TWIG4FCL1s27XC" width="230rem" height="380rem" frameborder="0" allowfullscreen ="true" allow="encrypted-media"></iframe>
            </div>
        </div>
        <br>

    
        <h3> Favorite Series </h3>
        <div class="row row-cols-1 row-cols-md-4">
            <div class="col mb-4">
                <div class="card bg-light">
                <img src="{% static 'e.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Elite : Netflix Series</h5>
                </div>
                </div>
            </div>
            <br>
            <div class="col mb-4">
                <div class="card bg-light">
                <img src="{% static 'dm.jpeg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Dare Me : Netflix Series</h5>
                </div>
                </div>
            </div>
            <br>
            <div class="col mb-4">
                <div class="card bg-light">
                <img src="{% static 'ge.jpeg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Get Even : Netflix</h5>
                </div>
                </div>
            </div>
        </div>
            
        

        <h3> Favorite Movies </h3>
        <div class="row row-cols-1 row-cols-md-4 ">
            <div class="col mb-4">
                <div class="card bg-light">
                <img src="{% static 'hp.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Harry Potter</h5>
                </div>
                </div>
            </div>
            <br>
            <div class="col mb-4">
                <div class="card bg-light">
                <img src="{% static 'kb.png' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Kissing Booth</h5>
                </div>
                </div>
            </div>
            <br>
            <div class="col mb-4">
                <div class="card bg-light">
                <img src="{% static 'rpo.jpeg'%} " class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Ready Player One</h5>
                </div>
                </div>
            </div>
        </div>
        {% endblock %}

story1/templates/nav.html
{% load static %}
<!DOCTYPE html>
<html> 
    <head> 
        <title> Raniah Nur Hanami </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"> </script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}">
    </head>
    <body> 
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{% url 'homepage:index' %}">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house-door-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M6.5 10.995V14.5a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5h-4a.5.5 0 0 1-.5-.5V11c0-.25-.25-.5-.5-.5H7c-.25 0-.5.25-.5.495z"/>
                        <path fill-rule="evenodd" d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                    </svg>
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu" aria-controls="navbarTogglerDemo02" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="menu">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:index' %}#gallery">Gallery</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:favorites' %}">Favorites</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" data-toggle="popover" href="{% url 'story1:index' %}"> Story 1</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" data-toggle="popover" href="{% url 'story5:courses' %}"> Courses</a>
                        </li>
                        
                    </ul>
                </div>
            </nav>
            <br>
            {% block story1 %}
            {% endblock %}
        </body>
        </html>

story1/templates/story1.html
{% extends "nav.html" %}
{% load static %}
<!DOCTYPE html>

<html> 
    <head> 
        <title> Raniah Nur Hanami </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}">
    </head>
    <body> 
    {% block story1 %}
        <img src="{% static 'photo.png' %}" class="photo">
        <h2> Raniah Nur Hanami </h2>
        <em> Saya adalah pribadi yang menyenangkan dan bersemangat. Saya yang senang berkomunikasi dengan orang lain 
            <br> sehingga cukup mudah beradaptasi dengan orang baru. </br>
        </em>

        <p> Nama panggilan : Rania atau Wawa </p>
        <p> NPM : 1906293291   </p>
        <p> Angkatan : 2019  </p>
        <p> Hobi : Olahraga, bermain, nonton film  </p>
        <p> Pendidikan :
            Universitas Indonesia : 2019 - sekarang 
            <p> &nbsp; SMAN 5 Bogor : 2016 - 2019 <p>
            <p> &nbsp; SMPN 4 Bogor : 2013 - 2016 </p>
        </p> 
            <a href="https://www.instagram.com/ranianhanami/" class="fa fa-instagram"></a>
            <a href="https://www.linkedin.com/in/raniah-nur-hanami-01336b194/" class="fa fa-linkedin"></a>
        </p>
        {% endblock  %}
    </body>
    

</html>

story5/templates/addCourse.html
{% extends "navbar.html" %}
    {% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class="form-group" >
            {{form.name.label_tag}} {{form.name}}
            {{form.lecturer.label_tag}} {{form.lecturer}}
            {{form.credit.label_tag}} {{form.credit}}
            {{form.room.label_tag}} {{form.room}}
            {{form.semester.label_tag}} {{form.semester}}
            {{form.description.label_tag}} {{form.description}}
        </div>
        <input href="{% url 'story5:add' %}" class="btn btn-secondary" type="submit" value="Add Course">
    </form>

    {% endblock %}
    </body>
</html>

story5/templates/story5.html
{% extends "navbar.html" %}
    {% block content %}
        <div class="card w-100">
            <div class="card-body">
                <h5 class="card-title fav">My Courses</h5>
                <p class="card-text">This page will be about the courses that I took</p>
            </div>
        </div>
        <br>
        <div>
            <a type="button" class="btn btn-secondary add" href="{% url 'story5:add' %}" role ='button'> Add Course</a>       
        </div>    
        <br>
        <div class="col lg-4">
            <table class="table table-responsive-lg table-striped ">
                <thead>
                    <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Lecturer</th>
                    <th scope="col">Credit</th>
                    <th scope="col">Room</th>
                    <th scope="col">Semester</th>
                    <th scope="col">Description</th>
                    <th scope="col">Delete Course</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in course %}
                        <tr>
                            <td>{{ c.name }}</td>
                            <td>{{ c.lecturer }}</td>
                            <td>{{ c.credit }}</td>
                            <td>{{ c.room }}</td>
                            <td>{{ c.semester }}</td>
                            <td>{{ c.description }}</td>
                            <td>
                                <a href="{% url 'story5:course_remove' id=c.id %}">
                                    <button class="btn btn-icon btn-secondary" > Delete </button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endblock %}

story6/templates/activity.html
{% extends "navbar.html" %}
{%load static%}
    {% block content %}
    <div class="card w-100">
        <div class="card-body">                
                <h5 class="card-title fav">My Activity</h5>
                <p class="card-text">This page will be about my activity</p>
            </div>
        </div>
        <br>
        <div>
            <a type="button" class="btn btn-secondary add" href="{% url 'story6:addActivity' %}" role ='button'> Add Activity</a>       
        </div>    
        <br>
        <div class="row w-100 justify-content-center">
            {% for actv in activity %}
            <div class="col-4 m-4 p-4 rounded border">
                <ul class="list-group">
                    <li class="list-group-item list-group-item-dark"> 
                        <b> {{ actv.activity }} </b> 
                    </li>
                    {% for prsn in person %}
                        {% if prsn.activity == actv %}
                            <li class="list-group-item">
                                <div class="d-flex justify-content-between">
                                    {{ prsn.person }}
                                        <a href="{% url 'story6:removeActivity' remove_id=prsn.id %}">
                                            <button class="btn btn-icon btn-danger" > - </button>
                                        </a>
    
                                    </button>
                                </div>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
                    <br>
                    
                    <a type="button" class="btn btn-secondary btn-sm" href="{% url 'story6:addPerson' person_id=actv.id %}" role ='button'> Join</a>   
            </div>
            {% endfor %}
        </div>

    {% endblock %}

story6/templates/addActivity.html
{% extends "navbar.html" %}
    {% block content %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group" >
                {{form.activity.label_tag}} {{form.activity}}
            </div>
            <input href="{% url 'story6:addActivity' %}" class="btn btn-secondary" type="submit" value="Add Activity">
        </form>
    {% endblock %}

story6/templates/addPerson.html
{% extends "navbar.html" %}
    {% block content %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group" >
                {{form.person.label_tag}} {{form.person}}
            </div>
            <input href="" class="btn btn-secondary" type="submit" value="Add Person">
        </form>
    {% endblock %}
    